return {
	["WoodenClub"] = {
		weaponType = "Mace",
		damage = 25,
		attackSpeed = 0.75,
		range = 6,
		maxCombo = 2,
	},
	--[[
	["IronMace"] = {
		weaponType = "Mace",
		damage = 35,
		attackSpeed = 0.8,
		range = 8,
	},
	["IronSword"] = {
		weaponType = "Sword",
		damage = 20,
		attackSpeed = 1,
		range = 6,
	},
	["IronAxe"] = {
		weaponType = "Axe",
		damage = 30,
		attackSpeed = 1,
		range = 7,
	},
    ]]
}
