return {
	["WoodenClub"] = {
		WeaponType = "Mace",
		BaseDamage = 25,
		AttackSpeed = 0.75,
		Range = 6,
		maxCombo = 2,
	},
	--[[
	["IronMace"] = {
		WeaponType = "Mace",
		BaseDamage = 35,
		AttackSpeed = 0.8,
		Range = 8,
	},
	["IronSword"] = {
		WeaponType = "Sword",
		BaseDamage = 20,
		AttackSpeed = 1,
		Range = 6,
	},
	["IronAxe"] = {
		WeaponType = "Axe",
		BaseDamage = 30,
		AttackSpeed = 1,
		Range = 7,
	},
    ]]
}
